services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: niooi
      POSTGRES_PASSWORD: abcde12345
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}