services:
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - 80:8088
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    container_name: backend
    build:
      context: ./backend/
      network: host
    restart: always
    ports:
      - 9099:9099
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://niooi:abcde@127.0.0.1:9432/postgres
    depends_on:
      - db

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

volumes:
  pgdata: 
