services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: niooi
      # ur a weirdo
      POSTGRES_PASSWORD: abcde
      POSTGRES_DB: postgres
    ports:
      - 0.0.0.0:9432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
